force-app/main/default/objects/Lead/fields/ABN_Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>ABN_Registered_Date__c</fullName>
    <description>The registration of the company&apos;s ABN number.</description>
    <label>ABN Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Applicant_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Entity_Type__c</fullName>
    <description>The type of applicant appling for the Loan.</description>
    <label>Applicant Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRUSTS</fullName>
            </value>
            <value>
                <fullName>SOLE TRADERS</fullName>
            </value>
            <value>
                <fullName>COMPANY</fullName>
            </value>
            <value>
                <fullName>PARTNERSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Asset_Manufacture_Year__c.field-meta.xml
<CustomField>
    <fullName>Asset_Manufacture_Year__c</fullName>
    <description>The Manufacturing year of the asset which user wanted to buy.</description>
    <label>Asset Manufacture Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>1998</fullName>
            </value>
            <value>
                <fullName>1997</fullName>
            </value>
            <value>
                <fullName>1996</fullName>
            </value>
            <value>
                <fullName>1995</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Asset_Supplier_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Supplier_Type__c</fullName>
    <description>The type of Supplier through will deal will happen.</description>
    <label>Asset Supplier Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEALER</fullName>
            </value>
            <value>
                <fullName>PRIVATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <description>The Asset name which borrower wanted to buy.</description>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCESS EQUIPMENT (BOOM/SCISSOR LIFTS)</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL FEED BIN</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL MACHINERY AND EQUIPMENT</fullName>
            </value>
            <value>
                <fullName>ARTWORK</fullName>
            </value>
            <value>
                <fullName>ATTACHMENTS FOR EARTHMOVING</fullName>
            </value>
            <value>
                <fullName>ATTACHMENTS FOR EARTHMOVING MACHINERY</fullName>
            </value>
            <value>
                <fullName>ATV</fullName>
            </value>
            <value>
                <fullName>AUDIO VISUAL</fullName>
            </value>
            <value>
                <fullName>BUSES AND COACHES</fullName>
            </value>
            <value>
                <fullName>CAMPER VANS</fullName>
            </value>
            <value>
                <fullName>CARAVANS</fullName>
            </value>
            <value>
                <fullName>CLASSIC CARS (LOADINGS APPLY)</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CNC MACHINES</fullName>
            </value>
            <value>
                <fullName>COFFEE MACHINES</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL MOTOR VEHICLES (UTES, VANS AND 4WDS)</fullName>
            </value>
            <value>
                <fullName>COMPRESSORS</fullName>
            </value>
            <value>
                <fullName>COMPUTER EQUIPMENT</fullName>
            </value>
            <value>
                <fullName>CONCRETE CUTTERS</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION AND EARTH MOVING EQUIPMENT</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION AND EARTH MOVING EQUIPMENT (NON-MINING)</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION EQUIPMENT (NON WHEELED &amp; NON TRACKED) ATTACHMENTS TO PRIMARY ASSETS</fullName>
            </value>
            <value>
                <fullName>CONVEYORS</fullName>
            </value>
            <value>
                <fullName>COOL ROOMS AND SPRAY BOOTHS</fullName>
            </value>
            <value>
                <fullName>DEMOUNTABLES AND SHIPPING CONTAINERS</fullName>
            </value>
            <value>
                <fullName>DETACHABLE GPS UNITS</fullName>
            </value>
            <value>
                <fullName>EDGE BENDERS</fullName>
            </value>
            <value>
                <fullName>ELECTRIC OR MOTOR VEHICLE USED FOR HIRE/RENTAL PURPOSES</fullName>
            </value>
            <value>
                <fullName>ENGINEERING AND TOOLMAKING</fullName>
            </value>
            <value>
                <fullName>ENGINEERING AND TOOLMAKING EQUIPMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ballon_Amount__c.field-meta.xml
<CustomField>
    <fullName>Ballon_Amount__c</fullName>
    <description>The Balloon Amount promised by the user to provide after certain interval of time.</description>
    <label>Ballon Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <description>The Amount Initially Deposited by the User</description>
    <label>Deposit Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/GST_Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>GST_Registered_Date__c</fullName>
    <description>The Date of Registration of GST of business or company.</description>
    <label>GST Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Guarantor_1_Residential_Status__c.field-meta.xml
<CustomField>
    <fullName>Guarantor_1_Residential_Status__c</fullName>
    <description>Guarantor 1 Residential Status</description>
    <label>Guarantor 1 Residential Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owning</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Repayment_Term__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Term__c</fullName>
    <description>The Term of Repayment selected by the user.</description>
    <label>Repayment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>84</fullName>
                <default>true</default>
                <label>84</label>
            </value>
            <value>
                <fullName>83</fullName>
            </value>
            <value>
                <fullName>82</fullName>
            </value>
            <value>
                <fullName>81</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>79</fullName>
            </value>
            <value>
                <fullName>78</fullName>
            </value>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>76</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>74</fullName>
            </value>
            <value>
                <fullName>73</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>69</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
            <value>
                <fullName>67</fullName>
            </value>
            <value>
                <fullName>66</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>63</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>61</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>59</fullName>
            </value>
            <value>
                <fullName>58</fullName>
            </value>
            <value>
                <fullName>57</fullName>
            </value>
            <value>
                <fullName>56</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <description>The Loan Amount Request by the user.</description>
    <label>Requested Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Used_Asset__c.field-meta.xml
<CustomField>
    <fullName>Used_Asset__c</fullName>
    <description>The Asset which borrower wants to buy is new or old.</description>
    <label>Used Asset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USED</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>NEW</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/borrowerQualificationLogik.cls
/**
 * Created by : Ritik Raghwanshi
 * Updated on : 16/10/2024
 * Updated by : Ritik Raghwanshi
 * Updated on : 16/10/2024
 * Desc : This function calls the borrower Qualification Logik Api created in Flask.
 */

public with sharing class borrowerQualificationLogik {
    public borrowerQualificationLogik() {
        
    }
    @AuraEnabled
    public static String analyse(String LeadId){
        try{
            Map<String, Object> rootMap = new Map<String, Object>();        
            Lead LeadObj = [SELECT ABN_Registered_Date__c, Applicant_Entity_Type__c, Asset_Manufacture_Year__c, Asset_Supplier_Type__c, Asset_Type__c, Ballon_Amount__c, Deposit_Amount__c, GST_Registered_Date__c,  Guarantor_1_Residential_Status__c, Id, Name,  Primary__c, ProductInterest__c, Rating, Repayment_Term__c, Requested_Amount__c, State, Status, Street, Title, Used_Asset__c FROM Lead WHERE Id =:LeadId LIMIT 1];
            List<Map<String, Object>> bodyList = new List<Map<String, Object>>();
            Map<String, Object> body = new Map<String, Object>(); 
            
            // START
            body.put('application_number', (LeadObj.Id == null)? '0' : String.valueOf(LeadObj.Id) );                                                                                            // Id
            body.put('Name', (LeadObj.Name == null)? '0' : String.valueOf(LeadObj.Name) );                                                                                      // Name
            body.put('amount_financed', (LeadObj.Requested_Amount__c == null)? '0' : String.valueOf(LeadObj.Requested_Amount__c) );                                         // Requested_Amount__c
            body.put('deposit_amount', (LeadObj.Deposit_Amount__c == null)? '0' : String.valueOf(LeadObj.Deposit_Amount__c) );                                               // Deposit_Amount__c
            body.put('balloon_amount', (LeadObj.Ballon_Amount__c == null)? '0' : String.valueOf(LeadObj.Ballon_Amount__c) );                                                  // Ballon_Amount__c
            body.put('repayment_term_month', (LeadObj.Repayment_Term__c == null)? '0' : String.valueOf(LeadObj.Repayment_Term__c) );                                               // Repayment_Term__c
            body.put('applicant_entity_type', (LeadObj.Applicant_Entity_Type__c == null)? '0' : String.valueOf(LeadObj.Applicant_Entity_Type__c) );                          // Applicant_Entity_Type__c
            body.put('asset_supplier_type', (LeadObj.Asset_Supplier_Type__c == null)? '0' : String.valueOf(LeadObj.Asset_Supplier_Type__c) );                                // Asset_Supplier_Type__c
            body.put('asset_type', (LeadObj.Asset_Type__c == null)? '0' : String.valueOf(LeadObj.Asset_Type__c) );                                                           // Asset_Type__c
            body.put('asset_manufacture_year', (LeadObj.Asset_Manufacture_Year__c == null)? '0' : String.valueOf(LeadObj.Asset_Manufacture_Year__c) );                       // Asset_Manufacture_Year__c
            body.put('usage_type', (LeadObj.Used_Asset__c == null)? '0' : String.valueOf(LeadObj.Used_Asset__c) );                                                           // Used_Asset__c
            body.put('gst_registered_date', (LeadObj.GST_Registered_Date__c == null)? '0' : String.valueOf(LeadObj.GST_Registered_Date__c) );                                // GST_Registered_Date__c
            body.put('abn_registered_date', (LeadObj.ABN_Registered_Date__c == null)? '0' : String.valueOf(LeadObj.ABN_Registered_Date__c) );                                // ABN_Registered_Date__c
            body.put('guarantor_1_residential_status', (LeadObj.Guarantor_1_Residential_Status__c == null)? '0' : String.valueOf(LeadObj.Guarantor_1_Residential_Status__c) );// Guarantor_1_Residential_Status__c
            
            body.put('Primary__c', (LeadObj.Primary__c == null)? '0' : String.valueOf(LeadObj.Primary__c) );                                                                     // Primary__c
            body.put('ProductInterest__c', (LeadObj.ProductInterest__c == null)? '0' : String.valueOf(LeadObj.ProductInterest__c) );                                             // ProductInterest__c
            body.put('Rating', (LeadObj.Rating == null)? '0' : String.valueOf(LeadObj.Rating) );                                                                                 // Rating
            body.put('State', (LeadObj.State == null)? '0' : String.valueOf(LeadObj.State) );                                                                                   // State
            body.put('Status', (LeadObj.Status == null)? '0' : String.valueOf(LeadObj.Status) );                                                                                // Status
            body.put('Street', (LeadObj.Street == null)? '0' : String.valueOf(LeadObj.Street) );                                                                                // Street
            body.put('Title', (LeadObj.Title == null)? '0' : String.valueOf(LeadObj.Title) );                                                                                   // Title
            //END
            
            // bodyList.add(body);             
            rootMap.put('body', body);    
            System.debug('Checking for deploy vikas Khede:');   
            System.debug('Body List Obj Map :'+bodyList);
            String requestBodyString = JSON.serialize(rootMap);
            
            HttpRequest req = new HttpRequest();
            req.setEndpoint('http://111.118.247.45:5000/api/request-rules');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('x-api-key', 'VALUE'); 
            req.setBody(requestBodyString);
            req.setTimeout(60000); 
            System.debug('Requestbody---'+ requestBodyString);
            Http h = new Http();
            HttpResponse res = h.send(req);
 
            System.debug('Response---'+ res.getBody());
            // Assuming res is an instance of HttpResponse
            String responseBody = res.getBody();
            

            // Deserialize the JSON string to a Map<String, Object>
            Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);

            for (String key : resultMap.keySet()) {
                for (String innerKey : ((Map<String, Object>)resultMap.get(key)).keySet()) {
                    // System.debug('Key: ' + innerKey + ', Value: ' + ((Map<String, Object>)resultMap.get(key)).get(innerKey));
                    System.debug('Key: ' + innerKey + ' ------>');
                    for(String innermostKey : ((Map<String, Object>)((Map<String, Object>)resultMap.get(key)).get(innerKey)).keySet()){
                        // System.debug('Key: ' + innermostKey + ', Value: ' + ((Map<String, Object>)((Map<String, Object>)resultMap.get(key)).get(innerKey)).get(innermostKey));
                        System.debug('Key: ' + innermostKey + ' ------>');
                        for(String innermostMostKey : ((Map<String, Object>)((Map<String, Object>)((Map<String, Object>)resultMap.get(key)).get(innerKey)).get(innermostKey)).keySet()){
                            System.debug('Key: ' + innermostMostKey + ', Value: ' + ((Map<String, Object>)((Map<String, Object>)((Map<String, Object>)resultMap.get(key)).get(innerKey)).get(innermostKey)).get(innermostMostKey));
                        }
                    }
                }
            }
            // Now, resultMap holds the JSON data as a Map


            LeadsLogikServices.LeadEligiblePlanMapperFunc(resultMap);

            system.debug('After Calling other func');


            return res.getBody();
        }
        catch(exception e){
            System.debug(e.getMessage());
            return null;
        }
        
    }
}