force-app/main/default/objects/Lead/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Debt_to_income_ratio__c.field-meta.xml
<CustomField>
    <fullName>Debt_to_income_ratio__c</fullName>
    <label>Debt to income ratio</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Interest_Rate_Calculations__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Calculations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The interest rate calculation is accurate to two decimal places.</description>
    <label>Interest Rate Calculations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Key_Facts_Sheets_Highlighted__c.field-meta.xml
<CustomField>
    <fullName>Key_Facts_Sheets_Highlighted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Key Facts Sheet is highlight the comparison rate in bold.</description>
    <label>Key Facts Sheets Highlighted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <label>KYC_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Non-Verified</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Disclosure_Statements__c.field-meta.xml
<CustomField>
    <fullName>Product_Disclosure_Statements__c</fullName>
    <label>Product Disclosure Statement Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <description>The Loan Amount Request by the user.</description>
    <label>Requested Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Requested_payslips__c.field-meta.xml
<CustomField>
    <fullName>Requested_payslips__c</fullName>
    <label>Requested payslips</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Residence_status__c.field-meta.xml
<CustomField>
    <fullName>Residence_status__c</fullName>
    <label>Residence status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Unconscionable_Conduct__c.field-meta.xml
<CustomField>
    <fullName>Unconscionable_Conduct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the lender pressures  borrower to sign a contract without fully understanding the terms.</description>
    <label>Unconscionable Conduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unfair_Contract_Terms__c.field-meta.xml
<CustomField>
    <fullName>Unfair_Contract_Terms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>the contract term allows the lender to unilaterally change interest rates without notice, Do you agree with it ?</description>
    <label>Unfair Contract Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/complianceLogik.cls
public with sharing class complianceLogik {
    public complianceLogik() {

    }

    @AuraEnabled
    public static String analyse(String LeadId){
        try{
            System.debug('LeadId : ' + LeadId);
            Map<String, Object> rootMap = new Map<String, Object>();        
            Lead LeadObj = [
                SELECT Id, Status,  Residence_status__c, KYC_Status__c, Debt_to_income_ratio__c, Requested_payslips__c, Credit_Score__c, Product_Disclosure_Statements__c, Key_Facts_Sheets_Highlighted__c, Interest_Rate_Calculations__c, Unconscionable_Conduct__c, Unfair_Contract_Terms__c FROM Lead WHERE Id =:LeadId LIMIT 1];
            List<Map<String, Object>> bodyList = new List<Map<String, Object>>();
            Map<String, Object> body = new Map<String, Object>(); 
            
            // START
            body.put('application_number', (LeadObj.Id == null)? '0' : String.valueOf(LeadObj.Id) );                                                                               // Id

            body.put('residence_status', (LeadObj.Residence_status__c == null)? '0' : String.valueOf(LeadObj.Residence_status__c) );                                            // Requested_Amount__c
            body.put('kyc_status', (LeadObj.KYC_Status__c == null)? '0' : String.valueOf(LeadObj.KYC_Status__c) );                                                              // KYC_Status__c
            body.put('debt_to_income_ratio', (LeadObj.Debt_to_income_ratio__c == null)? '0' : String.valueOf(LeadObj.Debt_to_income_ratio__c) );                                // Debt_to_income_ratio__c
            body.put('requested_payslips', (LeadObj.Requested_payslips__c == null)? '0' : String.valueOf(LeadObj.Requested_payslips__c) );                                      // Requested_payslips__c
            body.put('credit_score', (LeadObj.Credit_Score__c == null)? '0' : String.valueOf(LeadObj.Credit_Score__c) );                                                        // Credit_Score__c
            
            body.put('product_disclosure_statements', (LeadObj.Product_Disclosure_Statements__c == null)? '0' : String.valueOf(LeadObj.Product_Disclosure_Statements__c) );     // Product_Disclosure_Statements__c
            body.put('key_facts_sheets_highlighted', (LeadObj.Key_Facts_Sheets_Highlighted__c == null)? '0' : String.valueOf(LeadObj.Key_Facts_Sheets_Highlighted__c) );        // Key_Facts_Sheets_Highlighted__c
            body.put('interest_rate_calculations', (LeadObj.Interest_Rate_Calculations__c == null)? '0' : String.valueOf(LeadObj.Interest_Rate_Calculations__c) );              // Interest_Rate_Calculations__c
            body.put('unconscionable_conduct', (LeadObj.Unconscionable_Conduct__c == null)? '0' : String.valueOf(LeadObj.Unconscionable_Conduct__c) );                          // Unconscionable_Conduct__c
            body.put('Unfair_Contract_Terms', (LeadObj.Unfair_Contract_Terms__c == null)? '0' : String.valueOf(LeadObj.Unfair_Contract_Terms__c) );                             // Unfair_Contract_Terms__c
            body.put('CreditReportDuration', 2);                             // Unfair_Contract_Terms__c
            
            
            
            //END
            
            // bodyList.add(body);             
            rootMap.put('body', body);       
            System.debug('Body List Obj Map :'+bodyList);
            String requestBodyString = JSON.serialize(rootMap);
            
            HttpRequest req = new HttpRequest();
            req.setEndpoint('http://111.118.247.45:5002/api/request-compliance-rules');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('x-api-key', 'VALUE'); 
            req.setBody(requestBodyString);
            System.debug('Requestbody---'+ requestBodyString);
            Http h = new Http();
            HttpResponse res = h.send(req);
            System.debug('Response---'+ res.getBody());
            // Assuming res is an instance of HttpResponse
            // String responseBody = res.getBody();

            // Deserialize the JSON string to a Map<String, Object>
            // Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);

            // Now, resultMap holds the JSON data as a Map
            


            system.debug('After Calling other func');


            return res.getBody();
        }
        catch(exception e){
            System.debug(e.getMessage());
            return null;
        }
        
    }
}